POST http://localhost:3003/register
Content-Type: application/json

{ 
    "color": "laranja",
    "numberOfGears": 18,
    "mark": "Caloi",
    "model": "Trilha",
    "price": 2100
}
###

DELETE  http://localhost:3003/delete/fe7da168-903d-423b-be95-49786bff86e5
Content-Type: application/json
###

PUT http://localhost:3003/register/newprice/06598950-be9c-47a6-ae0f-f791bad888c3
Content-Type: application/json

{
    "price":900
}
###

GET http://localhost:3003/bikes
Content-Type: application/json
###

GET http://localhost:3003/bikes/amarela
Content-Type: application/json
###

GET http://localhost:3003/bikes/1000/2000
Content-Type: application/json
###