POST http://localhost:3003/register
Content-Type: application/json

{ 
    "color": "Branca",
    "numberOfGears": 18,
    "mark": "Caloi",
    "model": "Trilha",
    "price": 2500
}
###

DELETE  http://localhost:3003/delete/f125b3e9-b18b-4e9a-8f22-a43e955f3205
Content-Type: application/json
###

PUT http://localhost:3003/register/newprice/3b87dc6a-0945-45c2-af7c-daa84c538f73
Content-Type: application/json

{
    "price":800
}
###

GET http://localhost:3003/bikes
Content-Type: application/json
###

GET http://localhost:3003/bikes/amarela
Content-Type: application/json
###

GET http://localhost:3003/bikes/1000/2000
Content-Type: application/json
###